name: Build and Push Image

on:
  push:
    branches:
      - development
      - main

jobs:
  build-and-share:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io          
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: Build and push the Docker image
        run: |
          docker build . --tag ghcr.io/${{ secrets.GCR_USERNAME }}/${{ github.event.repository.name }}:development
          docker run ghcr.io/${{ secrets.GCR_USERNAME }}/${{ github.event.repository.name }}:development
          docker push ghcr.io/${{ secrets.GCR_USERNAME }}/${{ github.event.repository.name }}:development
          
